### ISSUE TITLE
Mudar referência para local ao repositório

### ISSUE THREAD

**Issue by rafaelcorsi** [Insper/travis-dashboard#3]
https://github.com/Insper/travis-dashboard/blob/2188e511ec95b51e680c05833bbaad9bdef52fdb/scrapper/main.py#L10

@liciascl @arnaldojr o ideal é que esse arquivo fosse local ao repositório, se editarmos o `config.json` do repositório o painel se atualize automático. Da forma atual ele ainda depende de mexermos na rasp.

**Comment by liciascl** [comment]
a gente deixou esse script pra fazer alterações remotamente no painel, o sistema executa esse script a cada boot.. Acha que atende?


https://github.com/Insper/travis-dashboard/blob/master/update/script.sh

**Comment by rafaelcorsi** [comment]
Corrigido
